### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by clhunsen** [se-sic/coronet#167]
### Description

With renaming and publishing coronet, we need to come up with a nice and cool logo. @ChristianKaltenecker  has developed some sketches, which I will post here for discussion. Thank you very much so far, @ChristianKaltenecker! 

### Ideas for the Implementation

![IMG-20190527-WA0002](https://user-images.githubusercontent.com/2649820/58861564-f1c28780-86ae-11e9-9f35-4be566a14270.jpg)
![IMG-20190527-WA0003](https://user-images.githubusercontent.com/2649820/58861566-f1c28780-86ae-11e9-80e1-b020ba724155.jpg)
![IMG-20190527-WA0004](https://user-images.githubusercontent.com/2649820/58861567-f25b1e00-86ae-11e9-9b3b-6e9cfb2f3833.jpg)
![IMG-20190527-WA0005](https://user-images.githubusercontent.com/2649820/58861568-f25b1e00-86ae-11e9-944b-3d23e6bf0cf0.jpg)

----------------------------
What do you have on your mind? Ideas, suggestions, (constructive) criticism, compliments, ...?

**Comment by ChristianKaltenecker** [comment]
Hey,

Here is another draft of the logo:
![coronet-logo](https://user-images.githubusercontent.com/5088560/73521893-71a01d80-4407-11ea-89fc-34ec2b79eeb0.png)
Currently, the logo is no vector graphic. However, I plan to create the logo as a vector graphic as soon as the details of the image are clear :-)
What do you think, @clhunsen and @hechtlC ?

Note: I have used the second font proposed by @clhunsen due to license issues with the first font.

**Comment by bockthom** [comment]
This is the current draft of the logo:

![coronet png-1](https://user-images.githubusercontent.com/5575176/78197046-8e4ae700-7484-11ea-9d47-9556d320a4bd.png)

What are your thoughts on it? Any further change requests or suggestions for improvements?
If not, then I am looking forward to getting this draft as our logo soon...

**Comment by clhunsen** [comment]
Hi everybody,

thank you very much for your effort and the new proposal! This is much appreciated. :hugs:  

> This is the current draft of the logo:
> 
> ![coronet png-1](https://user-images.githubusercontent.com/5575176/78197046-8e4ae700-7484-11ea-9d47-9556d320a4bd.png)
> 
> What are your thoughts on it? Any further change requests or suggestions for improvements?
> If not, then I am looking forward to getting this draft as our logo soon...

I really like the colors of this propsal. It seems that you have been inspired by our universities' colors. :wink: Also, the idea of placing the coronet to the side is execllent. :slightly_smiling_face: 

Nevertheless, I still stand by my previous point: I feel that the network structure is too complex and is kinda overwhelming. Furthermore, to this end, it may not be that memorable and iconic if it is used in isolation.

----


If you need to use a logo right now or in the near future, feel free to use any of the proposed ones (but likely the last proposal). You should place a "temporary logo" label or something similar for now though. 

---
 
Yesterday, I worked with my girlfriend on some small drafts for the logo as  I thought that her artist/painter personality might have some good ideas. We sketched some small drafts that may reflect the iconicness I had in mind a bit better. 
These drafts are here for discussion such that we may find a good solution in the end. :slightly_smiling_face: 

![draft-claus-1 svg](https://user-images.githubusercontent.com/2649820/78248167-6c854a80-74ec-11ea-8b90-2656820a84f2.png)
![draft-claus-2 svg](https://user-images.githubusercontent.com/2649820/78248170-6e4f0e00-74ec-11ea-8e2f-53c3f5751eb2.png)
![draft-claus-3 svg](https://user-images.githubusercontent.com/2649820/78248172-6ee7a480-74ec-11ea-91cb-61397ad10e24.png)

What are your thoughts?

**Comment by bockthom** [comment]
> I really like the colors of this propsal. It seems that you have been inspired by our universities' colors. :wink:

Yes. However, I don't really remember whether have chosen these colors on purpose or by chance :wink: 

> Nevertheless, I still stand by my previous point: I feel that the network structure is too complex and is kinda overwhelming. Furthermore, to this end, it may not be that memorable and iconic if it is used in isolation.

Yeah, I can understand that, makes sense to me.

> Yesterday, I worked with my girlfriend on some small drafts for the logo as I thought that her artist/painter personality might have some good ideas. We sketched some small drafts that may reflect the iconicness I had in mind a bit better.

Sounds good, thanks a lot - to you and also to your girlfriend.
> These drafts are here for discussion such that we may find a good solution in the end. 
> 
> ![draft-claus-1 svg](https://user-images.githubusercontent.com/2649820/78248167-6c854a80-74ec-11ea-8b90-2656820a84f2.png)
> ![draft-claus-2 svg](https://user-images.githubusercontent.com/2649820/78248170-6e4f0e00-74ec-11ea-8e2f-53c3f5751eb2.png)
> ![draft-claus-3 svg](https://user-images.githubusercontent.com/2649820/78248172-6ee7a480-74ec-11ea-91cb-61397ad10e24.png)
> 
> What are your thoughts?

Not bad, reflects the iconicness better, I like the ideas.

However, there are some characteristics of your drafts which can be further improved:
1. Drafts 1 and 2 make the crown look more like a paper boat than like a crown (or also like a duncecap, not sure if this is the correct word for caps used in carnival...). Hence, I would prefer draft 3 or something similar, which does not have those black internal lines that should symbolize an e-mail icon, if my intuition is correct.
2. The two node symbols (in each of the drafts) do not really provide an intuition for a real network -- two nodes are just two nodes. I really like the idea of making the nodes more explicit with different colors and different shapes, but two nodes are not enough to get the intuition of a network. I would imagine to have more nodes, maybe about 6 or 8 or even 10 or something around that. And then we can have several edges among them to form a cute network.
3. I am not sure about the background color. The background color in draft 2 is too dark, whereas the white (or transparent) background seems a little bit to bright -- this may change if we would have more nodes in the network.
4. I really like the new shape of the crown, looks catchier than the angular shape of the previous drafts. However, the new shape may not really fit to the coronet letters. I would like to keep the font as is. So, we need to make sure that the crown fits to the letters. With the current drafts, I have the feeling that the bottom of the crown is too curved to fit next to the letters (but I did not try it to put them next to each other, it could also be the case that my intuition is wrong here). Maybe there is an option to reduce the flexion of the bottom of the crown, in order to adjust it a little bit to be compatible with the font.

Summary: Great work and very good ideas. But I think we need to adjust it a little bit here and there.

@clhunsen Would you provide svg files of your drafts to @ChristianKaltenecker? Maybe he can also continue working on your drafts if he has enough time to do that.

**Comment by ChristianKaltenecker** [comment]
Hey folks,

I have finally invested some time to refine these logos and here we go (without labels first):
![draft-kalti-1](https://user-images.githubusercontent.com/5088560/90341677-ca30b400-e001-11ea-8f3d-8686e03417ce.png)
This one has one more node in the corona and the bottom border of the corona is now a straight line.
![draft-kalti-2](https://user-images.githubusercontent.com/5088560/90341704-0532e780-e002-11ea-80c9-d1122c17d7b1.png)
In this example, the bottom border is as before.
![draft-kalti-3](https://user-images.githubusercontent.com/5088560/90341711-11b74000-e002-11ea-96f1-53c3309c76c9.png)
This is another example with one more node. I have arranged it in such a way that it now looks like a filter, since you also filter a lot of data, right?

And because I couldn't ressist to bring some new ideas when arranging the nodes (my favourite):
![draft-kalti-happy](https://user-images.githubusercontent.com/5088560/90341735-3b706700-e002-11ea-9855-8d85d4f80c23.png)
I don't think that it needs further explanation.

Now, here examples 1+2 with the font:
![draft-kalti-1-text](https://user-images.githubusercontent.com/5088560/90341905-07964100-e004-11ea-99c3-dd25eb2d38cb.png)
![draft-kalti-2-text](https://user-images.githubusercontent.com/5088560/90341910-0bc25e80-e004-11ea-8e3e-b8fab5b8c6d4.png)
I know that this one is pixeled. But this is not important.
It's rather a question of how you want the bottom line.

So, what do you think, @clhunsen , @bockthom , @hechtlC ?

**Comment by bockthom** [comment]
Thanks a lot @ChristianKaltenecker for refining the logo drafts! 

I really like the following one, having a straight line at the bottom border of the corona (but I would prefer the triangle-shaped node to be in the middle instead of the circle-shaped one):
> ![draft-kalti-1-text](https://user-images.githubusercontent.com/5088560/90341905-07964100-e004-11ea-99c3-dd25eb2d38cb.png)

And I also really like the following one for multiple reasons :smile: In addition to the obvious reasons, I like the following one as its number of nodes and edges expresses the shape and structures of a complex network way more than the above one, which is simpler. However, if we stick to this one, we should adjust the size of the nodes and the thickness of the edges a bit :smile: 
> And because I couldn't ressist to bring some new ideas when arranging the nodes (my favourite -- I call it the happy face):
> ![draft-kalti-happy](https://user-images.githubusercontent.com/5088560/90341735-3b706700-e002-11ea-9855-8d85d4f80c23.png)

@clhunsen what are you thoughts on Christian's new drafts?

**Comment by clhunsen** [comment]
Some days ago, I thought that the coronet-like shape with a network inside seems to be too strict, the drafts look kind of forced somehow. :thinking: So, I say: Let's break with that for a moment and go another way to get some new ideas – by setting the network into the focus again.

I sketched some _drafts_, maybe these appeal to you and foster our idea process:
![coronet-logo_crown-network](https://user-images.githubusercontent.com/2649820/96186768-31a0ac80-0f3c-11eb-8ddc-ab7ebb99cbb0.png)

**Comment by bockthom** [comment]
Thanks a lot @clhunsen for working on our logo drafts again! They look really great, good job!

The new drafts look good in general. Nevertheless, the first draft looks a little bit too simple to me, but I really like the second and the third draft. However, we should make the lines thicker. If we put the logo next to the coronet letters, the lines would look very thin. So making them a little bit thicker would be fine. Would this be ok for you @clhunsen ?
> ![coronet-logo_crown-network](https://user-images.githubusercontent.com/2649820/96186768-31a0ac80-0f3c-11eb-8ddc-ab7ebb99cbb0.png)

@hechtlC What do you think about the new drafts?

@ChristianKaltenecker If Claus agrees on having thicker lines, would you please try a new draft of the crown next to the coronet letters to see the complete logo?

<sub><sup>[After refining the current drafts, we should come closer to a final decision. Refining logo drafts and ever recreating completely new drafts can be a creative, time-filling, and ever-lasting task, but we should not spend too much time on that. Having a logo would be nice to use it in slides and on Websites -- having a logo only after all slides and websites are finished will be not that useful any more.]</sup></sub>

**Comment by clhunsen** [comment]
> The new drafts look good in general. Nevertheless, the first draft looks a little bit too simple to me, but I really like the second and the third draft. However, we should make the lines thicker. If we put the logo next to the coronet letters, the lines would look very thin. So making them a little bit thicker would be fine. Would this be ok for you @clhunsen ?

As all this is just a draft until now, I am totally fine with making the lines thicker. I am also fine with varying the vertices in their shape and location, varying the lines, the colors, ... – very much similar to as I did with these drafts. :wink: 

> [After refining the current drafts, we should come closer to a final decision. Refining logo drafts and ever recreating completely new drafts can be a creative, time-filling, and ever-lasting task, but we should not spend too much time on that. Having a logo would be nice to use it in slides and on Websites -- having a logo only after all slides and websites are finished will be not that useful any more.]

I agree. Anyway, I have the feeling that we have a really good common ground with these newest drafts and that we are very close now. :grinning: 

@ChristianKaltenecker, I send you an e-mail with the source file of my drafts. I am eager to see your ideas for that.

**Comment by ChristianKaltenecker** [comment]
So, @hechtlC, @bockthom and I modified the logo until we came to the following version:
![coronet_logo](https://user-images.githubusercontent.com/5088560/100551357-2dc4b180-3280-11eb-9338-5d56ef70e80d.png)
The version with the 'coronet' label is as follows:
![Coronet_3](https://user-images.githubusercontent.com/5088560/100551705-c0fee680-3282-11eb-9595-10fb8969a660.png)
And, finally, I have also added a small version for the favicon (i.e., the logo shown in the browser tab):
![coronet_logo](https://user-images.githubusercontent.com/5088560/100551996-97df5580-3284-11eb-9ba1-a960e814dad8.png)

@clhunsen, what do you think?
@bockthom and @hechtlC: if you have further comments, just let me know.

**Comment by bockthom** [comment]
Wow, that looks great! :tada: 
I am completely fine with that. If it were up to me, I would take this version eventually as our official logo - without further changes.
But let's wait for other comments. 

Thanks for your efforts @ChristianKaltenecker!

**Comment by clhunsen** [comment]
Thanks for the new draft and your effort, @ChristianKaltenecker! :grinning::+1: To get some insights before commenting, I just sat down with my girlfriend to discuss the current drafts. In the end, relying on her artist skills, we felt like that the logo part and the text part feel apart and we need to let them appear more like one single unit. For this, we slightly adjusted font, edge weight, node sizes, and node shapes – and this is the result:

![coronet-logo_crown-network](https://user-images.githubusercontent.com/2649820/100936189-7040f500-34f1-11eb-9384-54c78319f818.png)
<img src="https://user-images.githubusercontent.com/2649820/100936481-e04f7b00-34f1-11eb-9f97-823e4db70e52.png" height="64">

We are still unsure about the colors, although, in our opinion, the Passau orange needed to be re-introduced to honor the origins of coronet. :slightly_smiling_face: 

<img src="https://user-images.githubusercontent.com/2649820/100936194-71722200-34f1-11eb-93e0-7357c341c3bf.png">

-------------------
What do you think?

**Comment by ChristianKaltenecker** [comment]
Happy New Year to you all.

I have now made the final adjustments after our meeting and I hope that this logo is now a good candidate for the logo.
Here is the logo without the font:
![coronet_logo_final](https://user-images.githubusercontent.com/5088560/104368300-2e599480-551c-11eb-8e66-8bb5857a3c42.png)
And here the version with the font:
![coronet_with_font_final](https://user-images.githubusercontent.com/5088560/104368386-49c49f80-551c-11eb-84c1-6989962e2ae5.png)
I will also add the small version if this one fulfills all our requirements^^

**Comment by bockthom** [comment]
Wow, the new logo (without the font) looks great. Thanks for your efforts @ChristianKaltenecker, the crown looks perfect to me. There are no further objects from my side.

However, we still need to work on the font (whose cursiveness still needs to be adjusted, which is not that easy to achieve for svg files...), hence, this will still take some time I guess, but we are on stretch.

So, after adjusting the font, I think we can finalize our logo (i.e., providing the svg file here and also generating a small favicon version with white background and radiused corners) -- but let's wait for the adjustment of the font.

**Comment by ChristianKaltenecker** [comment]
Glad to be of service. 
Together with Thomas, we further modified the font and think, that it works pretty well by now:
![coronet_with_font_final](https://user-images.githubusercontent.com/5088560/104964014-f18a1380-59db-11eb-81ec-6fd9158cfa92.png)

**Comment by bockthom** [comment]
> ![coronet_with_font_final](https://user-images.githubusercontent.com/5088560/104964014-f18a1380-59db-11eb-81ec-6fd9158cfa92.png)

Thanks @ChristianKaltenecker for your continued work on our logo! The logo together with the perfectly aligned font looks really great, even better than I have expected. So, I am glad now––I don't have any further change requests any more––if it was up to me, I would say: We finally have found our logo :tada: :partying_face: 

So, I am just waiting for the final acknowledgements: @clhunsen @hechtlC What do you think? Do you agree with this version going to be our new logo?
If everyone agrees, @ChristianKaltenecker and I will finally distribute the logo as svg file and prepare a favicon version.

**Comment by hechtlC** [comment]
So first of all thank you very much for the time invested @ChristianKaltenecker and @bockthom! The logo looks really good now! And if @clhunsen agrees as well, I think we have found our logo. So I have no further requests and would be fine with taking this.

**Comment by clhunsen** [comment]
I really like the new version. :slightly_smiling_face::+1: I am looking forward to a PR. :wink:

**Comment by bockthom** [comment]
As @clhunsen and @hechtlC have agreed on our current version of our logo, we finally have found **the** coronet logo! Hooray! :tada: :smiley:

Thanks to everyone who has participated in this journey to the creation of our logo, which has started more than 19 months ago. Special thanks to @ChristianKaltenecker for the vital, detailed, and work-intensive technical implementation of our ideas and, in particular, the endurance to support us. Also thanks to @clhunsen for the fundamental ideas and recurring refinements.

---

Before closing this issue and opening a PR, let me just list the different variants and formats of our logo we would like to have, to be prepared for various use cases in the future. @ChristianKaltenecker could you please provide us with the following variants of our logo and distribute them to us via e-mail:

- [ ]  The logo without font (svg & png)
- [ ]  The logo with font (svg & png)
- [ ]  A favicon version of the logo with white background with radiused corners (only without font)
- [ ]  The logo without font + white background with radiused corners (svg & png)
- [ ]  The logo with font + white background with radiused corners (svg & png)
- [ ]  An "inverted" version (i.e., white edges and white font, to be used when having a dark background) of the logo without font (svg & png)
- [ ]  An "inverted" version (i.e., white edges and white font, to be used when having a dark background) of the logo with font (svg & png)

Even if we did not vote on the last two (the "inverted" ones), I would like to have them for internal use to be prepared for potential use cases on dark background.

After distributing all these logo variants, we can finally start to integrate the logo into our `README.md` file and open a PR for that.
