### ISSUE TITLE
Wrong data path for range data objects

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#177]
### Description

I just encountered a situation in which the data path for range data objects is actually wrong.

(For time reasons, I will just explain how I think the problem occurs, but without checking whether the MWE is correct. This is just to document the issue, I will get back to this at a later point in time.)

### Steps to Reproduce or Minimal Working Example (MWE)

1. Build the `ProjectData` object and cut its data to same dates:
```R
project.configuration <- ProjectConf$new(DATA.PATH, ANALYSIS.RANGE.TYPE, CASESTUDY, ARTIFACT)
project.configuration$update.value("mails.filter.patchstack.mails", TRUE)
project.data <- ProjectData$new(project.configuration)

# cut the data from different data sources to overlapping ranges
project.data <- project.data$get.data.cut.to.same.date(data.sources = c("mails", "commits"))

commit.data <- project.data$get.commits()
```
As a consequence, `project.data` now is a `RangeData` object, as the cutting functionality internally uses the split functionality. The split functionality generates `RangeData` objects and updates the `project.configuration` regarding the split ranges etc. Up to now, everything is fine, the commit data is retrieved correctly.

2. Update project configuration, for example, add pasta data, and retrieve mail data afterwards.
```R
project.data$update.project.conf(updated.values = list("pasta" = TRUE))
pasta <- project.data$get.pasta()
mails <- project.data$get.mails()
```
This results in empty mail data, the mail data cannot be read, as the following warning states:
```R
Warning message:
In file(file, "rt") :
  cannot open file './testdata/results/threemonth/teststudy_feature/feature/001--2003-01/commits.list': No such file or directory
```
The reason for that is, that the `read` functions get the data path as parameter, which for `RangeData` objects is determined by:

https://github.com/se-passau/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-data.R#L1408-L1411

And `ranges.paths` contains the following, due to data cutting in the beginning:

```R
 ranges.paths [final]
  - value
    - 2003-01-14 21:44:38-2016-02-18 21:50:25 = 001--2003-01
```
However, this actually wrong, as the directory `001--2003-01` does neither exist, nor should it be used at all. This kind of ranges and range directories is related to Codeface ranges (and also to module `util-bulk`), but not to split ranges created by coronet. Therefore, the function `get.data.path` of `RangeData` objects does not return the expected data path.

**Actual behavior:** Data is to be read from a non-existing directory.

**Expected behavior:** `get.data.path` of `RangeData` objects should return the same data path as the corresponding project data. However, this does not respect the previous data cutting (or splitting, in general). Maybe it would be an idea to read in the data and then split it to the ranges set in the project configuration? Would this be an appropriate solution?

We should make this more flexible to be compatible with Codeface ranges (maybe additional boolean flag necessary) and data cutting. Also automatic data cutting/splitting could cause further trouble, but it is necessary to stay consistent with the remaining range data.

### Versions

This affects several versions, including the most recent one (3.6). As far as I have seen, this problem exists, at least, since version 3.0.

I just figured this out by chance. In my script, I just rearranged the order of the get and update-config statements, to avoid this situation. However, in general, for the long term, we should come up with a solution for this problem, even for consistency reasons.

**Comment by clhunsen** [comment]
> 1. [...] Up to now, everything is fine, the commit data is retrieved correctly.

This is not surpirsing as the splitting functionality is used underneath, which reads all data sources from disk before perfoming the actual splitting.

> 2. Update project configuration, for example, add pasta data, and retrieve mail data afterwards. [...]

Let's pretend that we configure the "correct" folder: When adjusting the data after splitting/cutting, the data needs to be read from disk (again) – _and_ be split/cut again. I am not sure if this is wanted and needed.

> The reason for that is, that the `read` functions get the data path as parameter, which for `RangeData` objects is determined by:
> 
> https://github.com/se-passau/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-data.R#L1408-L1411

This behavior stems from the rather old Codeface range folders, it was never expected to work for artificial RangeData objects that has been created by splitting/cutting.

> Maybe it would be an idea to read in the data and then split it to the ranges set in the project configuration? Would this be an appropriate solution?
>
> I just figured this out by chance.

This is funny, because the RangeData objects behave like this since we have introduced the splitting (and later, cutting) functionality. This has never been different. Reloading data for a RangeData object (unless it stems from an actual Codeface range folder!) has never been supposed to work as data needs to be loaded _and_ split for this.

To this end, I always initialized the needed commit/mail/... data, then split/cut the data. I told myself: Configuration and data loading happens always _before_ splitting/cutting, split data cannot be reloaded later.

I would have bet that this behavior is documented somewhere, but I have not found any reference... :thinking: Based on the resolution of this issue, this needs to be documented properly.

> We should make this more flexible to be compatible with Codeface ranges (maybe additional boolean flag necessary) and data cutting. Also automatic data cutting/splitting could cause further trouble, but it is necessary to stay consistent with the remaining range data.

I am totally with you. Apart from documenting this "problem", I just thought about a flag `locked` in both ProjectData and RangeData, which prevents updating the inherent data (loaded lazily beforhand) and which cannot be unset again (i.e., no unlocking possible). This way, the data path would not be relevant and users would be informed about impossible actions.

What do you think about that?

**Comment by bockthom** [comment]
> > 2. Update project configuration, for example, add pasta data, and retrieve mail data afterwards. [...]
> 
> Let's pretend that we configure the "correct" folder: When adjusting the data after splitting/cutting, the data needs to be read from disk (again) – _and_ be split/cut again. I am not sure if this is wanted and needed.

I am also not really sure what is needed in this case, but the current behavior is not what I would expect in this case. That's why I have opened this issue ;) Other users which have not been involved in the implementation of coronet do also not know about the current behavior... but more about this below.

> 
> > The reason for that is, that the `read` functions get the data path as parameter, which for `RangeData` objects is determined by:
> > https://github.com/se-passau/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-data.R#L1408-L1411
> 
> This behavior stems from the rather old Codeface range folders, it was never expected to work for artificial RangeData objects that has been created by splitting/cutting.

This is true. But we also never tested what does happen in such a situation of artificial RangeData objects -- as we knew that we should not do it like that, we never did it. However, "it was never expected to work" should not be an argument for keeping the current behavior as only insiders know are aware of that. That's why i think we should improve the behavior here.
> 
> > Maybe it would be an idea to read in the data and then split it to the ranges set in the project configuration? Would this be an appropriate solution?
> > I just figured this out by chance.
> 
> This is funny, because the RangeData objects behave like this since we have introduced the splitting (and later, cutting) functionality. This has never been different. Reloading data for a RangeData object (unless it stems from an actual Codeface range folder!) has never been supposed to work as data needs to be loaded _and_ split for this.

Here I completely agree with you, again. The problem here is: We first introduced the splitting functionality and later re-used it for the cutting functionality. For the splitting functionality, the behavior of the RangeData objects is totally correct, as I have in mind that reading new data after splitting does not make sense. However, for the cutting functionality, this is different: As a default, I add the function call to `get.data.cut.to.same.date` to every script at the very beginning as it is an important aspect to first unify the date ranges before doing anything else. And here is the problem: Calling this function results in a RangeData object -- which is supposed to behave like the initial ProjectData object after removing the data which is outside the unified date ranges. So, in this case, I first would cut the data (as always, according to my default template) and then decide what to use especially in addition - e.g., using PaStA data, as PaStA data is not affected by data cutting at all.

In the above stated code example, I used the cutting functionality to cut mail (!) and commit data. That is, the mail data have already been read before cutting/splitting, as the cutting functionality automatically reads the data for cutting them. But reading the PaStA data afterwards (which is *not* affected by cutting/splitting at all) leads to a problem here... And this something which definitively should be fixed somehow...
> 
> To this end, I always initialized the needed commit/mail/... data, then split/cut the data. I told myself: Configuration and data loading happens always _before_ splitting/cutting, split data cannot be reloaded later.

In general, I agree with you -- for the data sources which are affected by splitting. But again, cutting the data automatically loads the data.
> 
> I would have bet that this behavior is documented somewhere, but I have not found any reference... thinking Based on the resolution of this issue, this needs to be documented properly.

I totally agree with you. I did not check whether this is documented or not - but even if it would be documented, I only would assume that this hold for data sources which are affected by splitting, not for PaStA data, for instance.
> 
> > We should make this more flexible to be compatible with Codeface ranges (maybe additional boolean flag necessary) and data cutting. Also automatic data cutting/splitting could cause further trouble, but it is necessary to stay consistent with the remaining range data.
> 
> I am totally with you. Apart from documenting this "problem", I just thought about a flag `locked` in both ProjectData and RangeData, which prevents updating the inherent data (loaded lazily beforhand) and which cannot be unset again (i.e., no unlocking possible). This way, the data path would not be relevant and users would be informed about impossible actions.
> 
> What do you think about that?

Such a "locked" flag would be an option in general. But I think that this does not really help in the situation in which the PaStA data is loaded afterwards. Again, as the PaStA data (same holds for synchronicity, and possibly also other data sources in the future) is not affected by splitting, there should be the possibility to add it even after cutting the remaining data to unified date ranges.

I have some suggestions how we could achieve that:

Option 1: Change the behavior of the reading functionality to be able to read the data even after splitting - the range data object should know its range bounds, so it should be possible to re-read the data and cut it to exactly those range bounds.

Option 2: If you want to keep the read functionality for RangeData objects as it is now, then we could introduce something like a new class CutData which allows re-reading data and automatically cuts it. (Maybe this modeling violates the Liskov substitution principle, I am currently not sure about that, but that would solve our problem, I guess).

The locking option would be ok if we would forbid adding additional data sources not affected by splittings. However, for the moment, I don't really like this option.

So, what is your opinion on that @clhunsen @hechtlC ?

If you think that the locking option is the best option, we can also go for that one (we then have to make sure that reading data from Codeface ranges still is possible etc.) - but to me, it sounds more intuitive for a user to have the possibility to the read additional data even after data cutting  - and therefore, I would suggest Option 1 or Option 2.

**Comment by hechtlC** [comment]
> In the above stated code example, I used the cutting functionality to cut mail (!) and commit data. That is, the mail data have already been read before cutting/splitting, as the cutting functionality automatically reads the data for cutting them. But reading the PaStA data afterwards (which is not affected by cutting/splitting at all) leads to a problem here... And this something which definitively should be fixed somehow...

I have a whole other proposal. Can't we just exclude the data sources that are not affected by splitting or cutting? When there is mail or commit data which is split or cut then the methods for reading and merging PaStA data should not re-read these data sources. So can't we just make it that the merging of such unaffected data sources (PaStA, synchronicity, ...) does not care whether the data object is a RangeData object or a normal one? That should fix all the problems regarding this. Or am I seeing something completely wrong?

**Comment by hechtlC** [comment]
Ok so I have just debugged the problem described by @bockthom. There are a couple of issues and I propose two different strategies to fix this.
The main problem regarding the re-reading of data sources that are not affected by splitting is that whenever we re-set a configuration parameter, we reset the complete environment. So when adding the PaStA data after splitting, there is no mail or commit data available. This has to be re-read then which dos not work for the above discussed reasons. 
But let's look at an example why the adding of PaStA data at a later time could be useful:
Say we analyze a large project regarding the mail and commit data. This can take quite some time. And at a later point in the analysis we notice that the PaStA data (for example) could give us useful insights regarding the interplay of mails and commits. Now we have to change the analysis and start from the top, which can take a lot of time. This could be fixed if we were able to add the PaStA data on the fly.

So the two strategies that could be used to implement this:

1. Exclude the non-splitting dependent data sources (PaStA, synchronicity, ...) from the routine that the whole environment gets reset if we change the configuration parameters. This could either be realized by separate functions to add these or by excluding them in the update.project.conf function. Then we would be able to add these at a later point in the analyses without causing any other problems.

2. Make split data re-readable by saving the bin information and splitting them after re-reading them into the prior existent bins. This would be a more extensive change to the code-base and the functionality. Then we could add the proposed locking configuration to prevent this from happening unintentionally.

Personally, I prefer the first solution as it is more intuitive and a less extensive change to the project.
What do you think @clhunsen @bockthom?

**Comment by hechtlC** [comment]
So after a further meeting with @bockthom and @clhunsen, we decided on an approach for this issue. I'm documenting this here but please correct/complete my description if something is wrong or missing.

1. We add a flag to the RangeData class that saves whether the object was created using range data (Codeface ranges) or by splitting/cutting a complete dataset. With that we make the data paths for re-reading the data better accessible. When the object is built from range data, we use the data path to the codeface-range folders and otherwise the "normal" data path.

2. We make the data sources that are not generally affected by splitting (PaStA, synchronicity, author data) readable at any time of an analysis. This gives us the possibility to add these data sources even if the main data sources (mails, commits, issues) are already in use. This is possible since the additional data sources do not affect the split data in any other way than adding it to the existing data.

3. Add a locking functionality as documented in #179.

Thanks to @bockthom and @clhunsen for the constructive discussion on this topic! I will implement this this week.

**Comment by bockthom** [comment]
Today, @hechtlC and I have further reflected about the previous decisions, or to be more concrete, the ideas proposed in the [previous comment from 20 Apr 2020](https://github.com/se-sic/coronet/issues/177#issuecomment-616361688) and have adjusted our ideas, which we will explain in the following (just for documentation reasons, to not forget about the details). Let's discuss this in our meeting next week in detail.

First of all, part 1. of the previous comment remains untouched. (Part 1. deals with the wrong data path for RangeData objects, as explained above).

Second, regarding part 2., we now propose the following solution:

- As data paths are to be fixed in part 1., we can read in data also for RangeData objects. However, this is only necessary if certain data are not yet read (e.g., `NULL`) or empty (`nrow(data) == 0`). For example, when calling `get.pasta()`, we need to adjust the condition for reading the data from https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-data.R#L912 to 
    ```R
    if (is.null(private$pasta) || nrow(private$pasta) == 0) {
    ```
    This needs to be adjusted similarly for all the other data sources.
- When calling getters on a RangeData object and data needs to be read as it does not yet exist (reading e-mail, commit, or issue data, but not (!) additional data sources), the read data needs to be cut to the range which is stored in the private `range` attribute of the RangeData object.
- As we enable reading data in RangeData object, we don't need to read them all when splitting data. For example, we currently read all (additional) data sources when splitting data, even if we don't need certain data sources, as can be seen here:
    https://github.com/se-sic/coronet/blob/bf8b331cd874f6fef787af0a6ad69c2a0496d3bb/util-split.R#L62-L77
    This is not necessary any more, as we can read the needed data lazily on demand. Hence, we can reduce runtime and memory consumption due not reading unneeded data sources. (Please check that in all the data-splitting functions.)
- Last but not least, as adding or removing additional data sources does not affect the remaining data, changing the corresponding configuration parameters in the ProjectConf should not reset the remaining data. This holds for the configuration options `commit.messages`, `synchronicity`, and `pasta` (and potentially also for `synchronicity.time.window` if there was no synchronicity data before, but this needs to be checked in detail). That is, when calling `update.project.conf` or `set.project.conf.entry` and only the entries regarding the additional data sources are set/updated, then we **don't** reset the environment. However, if any of the other ProjectConf options is set/updated, the reset of the environment is still necessary.

As we only re-read data if it is not available yet, there is no need for the locking feature any more (if we haven't overlooked anything here). As a consequence, part 3. of the previous comment, and also issue #179 are not necessary any more. Let's discuss this again, but if we don't recognize any special need for the locking feature, then let's just omit it.

Let's see if these suggestions endure the discussion in our next meeting :smile: 

---

While reflecting on the steps listed above and viewing at particular parts of the code, we spotted some other issues and bugs in the current implementation, which I will list in a separate issue soon (to not make this issue even more confusing).

**Comment by clhunsen** [comment]
Nice ideas, @bockthom and @hechtlC! As far as I remember the code base, you have considered everything. But, please do not let me swear on that. :wink::grin: 

I just had one thought: If you do not read data during splitting anymore, as it is not needed anymore (see your Point 3), then you do not need to adjust the conditions that determine whether a data source is not read already (Point 1), do you? If data is not read already, the private field has the value `NULL`, otherwise, the field is initialized with something (e.g., a data.frame).

**Comment by bockthom** [comment]
> Nice ideas, @bockthom and @hechtlC! As far as I remember the code base, you have considered everything. But, please do not let me swear on that. winkgrin

Thanks for your comment on that @clhunsen. It's good to know that you also think that our idea should work :smile: 
> 
> I just had one thought: If you do not read data during splitting anymore, as it is not needed anymore (see your Point 3), then you do not need to adjust the conditions that determine whether a data source is not read already (Point 1), do you? If data is not read already, the private field has the value `NULL`, otherwise, the field is initialized with something (e.g., a data.frame).

We need to adjust these conditions to get rid of empty data frames which might have been created before. Let's think about the following exemplary scenario:

One doesn't enable the `"pasta"` configuration option but calls `get.pasta()`. As PaStA data is not enabled, an empty data frame is created and returned. If I then enable `"pasta"` afterwards and call `get.pasta()` again, then the PaStA data is not read again as it seems to be already cached as `private$pasta` isn't `NULL`. However, in such a case, we actually want to read the PaStA data instead of returning the empty data frame. Hence, we need to adjust the condition mentioned above. (We already reflected whether this could have any side effects, but we did not identify such: If the actual PaStA data is empty, re-reading it will still end up in an empty data frame. And if there is actual PaStA data, then we really need to read it to get rid of the empty data frame in our cache.)

Does this justification sound reasonable to you?

**Comment by clhunsen** [comment]
> Does this justification sound reasonable to you?

Yes, it does. In my studies, adjusting the ProjectConf after reading data was never a use case, so I never thought about such scenarios. Thanks for clearing this up for me, @bockthom! Anyway, we now have a good documentation for the reasons of this upcoming change within this issue. :wink:

**Comment by JoJoDeveloping** [comment]
> also issue #179 are not necessary any more

so can we close #179?

**Comment by bockthom** [comment]
> so can we close #179?

Let's wait until we have further discussed our ideas and until you have finished the corresponding implementation, to be sure that we did not forget about anything here.

**Comment by bockthom** [comment]
@nlschn just pointed out that we currently have no possibility to extract which data sources are already read. However, we need such an option to be able to get and split only the read data sources.

After a short discussion with @hechtlC, we came up with the following idea:
Let's have a new public function in the ProjectData class that returns a vector stating which data sources (including additional data sources) are read. A data source is treated as "not read" if the corresponding private variable is `NULL` or the dataframe is empy (`nrow` == 0).
This way, it should be possible to find out which data sources have already been read before splitting and we only get and split them during the splitting routine.

**Comment by clhunsen** [comment]
> After a short discussion with @hechtlC, we came up with the following idea:
> Let's have a new public function in the ProjectData class that returns a vector stating which data sources (including additional data sources) are read. A data source is treated as "not read" if the corresponding private variable is `NULL` or the dataframe is empy (`nrow` == 0).
> This way, it should be possible to find out which data sources have already been read before splitting and we only get and split them during the splitting routine.

We have function `ProjectData$get.cached.data.sources()`, which has been introduced to do that. If I remember correctly, we planned to use it in the splitting module later. :thinking: If you want to and think it is needed, you could expand it with the mentioned additional check (`nrow(x) == 0`). 

https://github.com/se-sic/coronet/blob/a7f4123dcb86a7a0f76adf791b66a7d9c24f7647/util-data.R#L1035-L1060

----

On another page, I remember that we had a discussion on this additional check, but I do not remember neither the specific content nor the result. Can you please remind me, @bockthom?

**Comment by bockthom** [comment]
> We have function `ProjectData$get.cached.data.sources()`, which has been introduced to do that. 

Thanks for pointing this out @clhunsen and making us aware of that function. :+1:  
I did not even remember that we have such a function (and, to the best of my knowledge, also @hechtlC did not remember any more, at least not during our discussion). I also have scrolled through the file yesterday and even did not recognize this function, but it really seems to exist :smile: 
@nlschn Could you please check if the function `get.cached.data.sources` can be used in your implementation? Anyway, this function needs to be adjusted as it also is a little bit outdated––for example, the commit-message data source is not listed there, as far as I see. (Maybe it is worth to additionally have a look whether we have missed that somewhere else, but I guess we are already headed in the right direction...)

> On another page, I remember that we had a discussion on this additional check, but I do not remember neither the specific content nor the result. Can you please remind me, @bockthom?

We had discussed about the `nrow(x) == 0` check further above in this issue discussion here: https://github.com/se-sic/coronet/issues/177#issuecomment-808146145. Is this the discussion you were looking for?
Anyway, as the referenced comment only discusses the additional data sources, let me just add a comment on the remaining data sources: It might not be necessary to add this check for the main data sources, but we would like to add it for consistency reasons to treat main and additional data sources similarly. And it does not really make a difference: If the data frame is meant to be empty, it does not cost that much to read the empty data again. If the data frame is empty but there are actual data (for whatever reason), we keep the possibility to read the data later on. But we still have to check if there are certain cases in which we could run into problems––but we will hopefully see that when having a look at the new implementation and when reviewing the corresponding pull request.

**Comment by bockthom** [comment]
In our meeting today, we identified two problems with our suggested implementation (thanks to some failing tests :smile:):

1. We have a potential problem when reading in data in RangeData objects after activity-based data splitting. In particular, we end up in a problem when there are multiple activities at the same time, so just splitting the data to the determined ranges does not help in this situation, as we need to check which activities from those "participating at the same time" should be part of the range. For now, I have two ideas: 
**_Idea 1:_** When reading data in RangeData object, not only access the `range` attribute, but also check what is stored in the splitting information `get.splitting.info()` of the corresponding `ProjConf` object. If the `type` attribute is `activity-based`, then we should do another approach than we do for time-based splitting. In this case, we should take the activity amount into account and determine/adjust the resulting data frames accordingly, so that we respect the activity amount and construct the data frame correctly. This should, hopefully, fix the activity-based-splitting-related test failures. (Btw, this would be the first time that we actually use the `splitting.info`, so it really seems that we really can derive a benefit from that, such like I have known that all along :wink: 
**_Idea 2:_** If Idea 1 does not lead to a solution (what I don't expect, but still can happen), then we would need to exclude activity-based split RangeData objects from re-reading data afterwards, which would distort our new concept of how to read and split data. So, if possible, I would like to avoid this scenario.

2. We also have identified another problem in the `equals` function which lets some tests fail: In the past, we expected that data objects are different when certain data.sources are not read or when their data frame is empty. However, as we now treat missing data (`NULL`) and empty data (`nrow(data) == 0`) equally and we check for existing data in our `equals` function, we now get failing tests as we expect that missing data is not equal to empty data. Again, I have two ideas how to fix that problem:
**_Idea 1:_** Ignore the problem and treat missing data and empty data equally. Hence, two data objects are equal even if, for example, their mail data is `NULL` in the one object and an empty data frame in the other object. However, you might feel worried as the data objects aren't really equal. If so, we could also fix this worries by initializing everything with an empty data.frame instead of `NULL`, to stay consistent with what our expectations on the concept of "equality" are. 
**_Idea 2:_** Distinguish between empty and missing data. Then we need to add a flag `treat.empty.data.as.missing.data` to the fucntion `get.cached.data.sources`, which defaults to `TRUE` but when the function is used in the `equals` function we set this parameter `FALSE`.

@hechtlC @clhunsen Any suggestions which of the ideas you would prefer, especially for problem 2? (for problem 1 it is obvious that we try Idea 1 if possible). We need to come up with a decision soon, while @nlschn is trying to find out why also some other tests fail in his implementation in PR #201...

**Comment by clhunsen** [comment]
> We had discussed about the `nrow(x) == 0` check further above in this issue discussion here: [#177 (comment)](https://github.com/se-sic/coronet/issues/177#issuecomment-808146145). Is this the discussion you were looking for?

Yes, this was the discussion I was looking for. Thanks for looking that up. My memory was like a black hole in the moment I wrote my question. :sweat_smile:  

> (for problem 1 it is obvious that we try Idea 1 if possible)

Agreed. :slightly_smiling_face: Using the `splitting.info`sounds reasonable and should provide all information that is needed. Otherwise, you could extend the `splitting.info` with the information you need. :wink:  

> Any suggestions which of the ideas you would prefer, especially for problem 2?

I do not have a good feeling about both ideas for Problem 2 somehow. Not sure why exactly... :thinking: One of the main features of coronet always was the lazy loading of data, including the ability to *not* read data if not really needed. When treating empty and missing data equally, the consequence is that, in the future, data is read by means of precaution, isn't it? This would contradict one of the (maybe formerly!) main features of coronet. Think about Linux as a project: you do not really want to re-read all commits and mails if not necessary, right?

The question is how can we improve the current data structures (i.e., `NULL` values for uninitialized data sources and timestamps) to make sure that data is not read from disk if not actually needed. Here, are my brainstorm ideas:
- Treat main and additional data sources differently: When re-cutting data, additional data sources are re-read from disk – completely. As they augment the main data sources, this is quite easy in comparison to reading the main data sources, I guess.
- I like the new parameter to the method `ProjectData$get.cached.data.sources()`, but make really sure that `TRUE` is the right choice for the default value. But, this decision is dependent on the outcome of this discussion actually.
- Return `NULL` when getting data that is not configured (e.g., call `get.pasta()` with `pasta = FALSE` in the configuration). But, maybe, only for additional data sources and not main sources... :thinking:  
- Remove the configuration parameters for additional data sources and control everything by edge attributes and column selection.
- When activating PaStA data afterwards, the user could be "forced" to use the method `ProjectData$set.project.conf.entry`, where we could reset the PaStA data to make sure that re-reading is possible and successful.
- Introduce a method to reset (single) data sources, for example, `ProjectData$reset.data.source(data.source = c("commits", ..., "pasta")`. This way, users could reset a data source to force a re-read from disk in a case you described [here](https://github.com/se-sic/coronet/issues/177#issuecomment-808146145) (`ProjectData$reset.environment()` could use this method then). This is likely the best one of my brainstorming ideas yet. :sweat_smile: As I said before, enabling PaStA data after reading them already was never one of my use cases, but support for this use case could be achieved with this idea.

In the end, it is likely worth to investigate on how we can ensure that missing and empty data is distinguished. We just need to dentify all use cases where data is to be reset to ensure consistent data. That is, when enabling PaStA after reading its data already, the cached PaStA data needs to be reset (manually or even automatically) and we are safe, I guess. 
I am not sure whether I have thought of everything. :wink:

**Comment by bockthom** [comment]
Thanks for you comments @clhunsen. I agree on your comments regarding problem 1. However, before I will have a detailed look at your ideas on how to solve problem 2, let me first understand what your concerns are:

> When treating empty and missing data equally, the consequence is that, in the future, data is read by means of precaution, isn't it? This would contradict one of the (maybe formerly!) main features of coronet. Think about Linux as a project: you do not really want to re-read all commits and mails if not necessary, right?

Unfortunately, I don't get your point here. From a practical point of view, treating empty and missing data equally does, imho, not lead to any problem when reading or re-reading data. The problem I have stated is a rather philosophic question whether we agree two data objects to be equal in the `equals` function where a data source has value `NULL` or an empty data frame.
For reading the data, it does not make a difference:
- If the data is `NULL`, read it, as it was not present before.
- If the data is an empty data frame, re-read it, as it might have not been configured before. In the case that the data is actually empty, we again result in reading an empty data frame, which is not costly. In the case that there is actual data (and, in the case of additional data sources, when we have configured to read them), then we actually want to read the data.

So, I don't understand your argument concerning the Linux project: Commits or e-mail are never re-read -- if we need them, we read them, and then we have them. No need for re-reading. If we don't need them, we won't read them, as it has already been implemented before, there is nothing going to change for the main data sources. (To be honest, there is one change with respect to splitting: Formerly, mail and commit data have been read all the time before splitting, even if one did not need them. The new implementation doesn't read anything except for the split basis. This way, we avoid reading data that is not needed. A potential drawback would be that if I read the commit data later on after splitting on mails, then I would need to read the commit data for every range separately, which adds a high overhead. However, this could me mitigated by reading the commit data already before splitting, for example via cutting data sources to same ranges (which is highly recommended to be done always at the beginning of an analysis). So, the only drawback we have, namely that we read data multiple times when we read the data after splitting, can be neglected as usually this kind of data should already have been read before so that the problem shouldn't happen that often, but we provide the possibility to the user to also do it afterwards (even if it causes overhead) and, more importantly, we don't read data automatically any more that is never used) But again, this is not the problem I was referring to. This has nothing to do with the philosophic question whether empty and missing data are equal. 

So, again, the only question is whether the `equals` function should distinguish between empty or missing data to treat objects as equal. From a practical view, there is no difference in reading or re-reading the data, so we don't need to think about that nor change the ongoing implementation. It's just targeting the `equals` function and whether we want to data objects to be treated as "equal".

**Comment by bockthom** [comment]
And I already had a very quick look at your ideas @clhunsen: All of them sound reasonable and we are really thankful for new ideas, this is really appreciated. However, unfortunately, most of the ideas you have stated would need us to change major parts and concepts of coronet, which are not targeted by the little problem we are taking about here. So, we don't have the resources to change everything in how any data source is configured in coronet (keep in mind that this would also involve handling corner cases and changing tests, etc.), and therefore most of your ideas are too costly to implement (and would also involve too much changes for current users), I am sorry for that. What we need is a **_quick and easy-to-implement solution_** without that many breaking changes (which also does not involve changes to existing scripts that depend on coronet), so that we can finish the work on this issue as fast as possible. So let's not open Pandora's box but stick to question of whether empty and missing data should be treated "equal" in the "equals" function or not.

---
Independent from the actual problem, I like the idea of providing a function to reset single data sources. Nevertheless, this can already be achieved in the current implementation of coronet by calling the corresponding setter function, but maybe it could be more intuitive for the user to have a separate function which does this. As this function needs to be called manually anyway and the currently existing setters can already be used to achieve the same result, such a function is not necessary, but let's keep it in mind for future improvements (beyond of fixing this issue).

**Comment by clhunsen** [comment]
> So let's not open Pandora's box 

Agreed. I just wanted to share my thoughts. There are many things mixed into and dependent on this tiny question and the chosen answer – plus I am not _that_ into all coronet matters these days... :sweat_smile: Wow, I really miss our weekly meeting with the students... :blush: 

> but stick to question of whether empty and missing data should be treated "equal" in the "equals" function or not.

In my humble opionion, I would say: "no". But I could understand if you come up with a different opinion and answer in the end. :slightly_smiling_face: 

> Independent from the actual problem, I like the idea of providing a function to reset single data sources. Nevertheless, this can already be achieved in the current implementation of coronet by calling the corresponding setter function

Yes, you are right basically, but this only works in all cases _iff_ empty and uncached data sources are treated equally since passing `NULL` to a setter initializes the data source with an empty data.frame and does not reset it to `NULL`. My idea was to provide a method that sets the data sources to `NULL`.

**Comment by hechtlC** [comment]
So I just thought about this and talked to @bockthom.
For Problem 1 I agree that we try Solution 1.

For Problem 2: @bockthom and I came to the conclusion that the best and easiest way to solve this is to automatically initialize all data sources (configurated or not) with the corresponding empty data frame. This does not create overhead and is easy to do. Since we can then only manually change these data sources through the setters, the fields should never contain `NULL`. The only thing we have to do then is to change the function `reset.environment` such that all data sources are just reset to the empty data frame. This is the best option in our opinion as we avoid the problem (and all possible problems) with `NULL`.

**Comment by nlschn** [comment]
When trying to set the data to an empty data frame when resetting, the data tests fail, because some column types do not match anymore with the ones from `create.empty.mails.list()` and its corresponding functions from util-read.R. Is there an elegant way to circumvent this issue or do I have to adjust the column types manually? 

For example this concerns the 'pasta' and 'revision.set.id' columns of the mails, which, after resetting, both appear to have type "character" instead of "logical"

**Comment by nlschn** [comment]
And regarding some of the failing tests, I stumbled upon another issue: There are tests that try to build networks, having set the data to NULL (internally the setter resets this to an empty data frame). However, at some point, the networkbuilder calls either `get.mails()`, `get.commits.filtered` or `get.issues.filtered`, which in turn call the respective getters, that now load the data, if it is null or empty (ignoring the issue above) which overall leads to the resulting networks being not empty anymore. Is this desired behaviour?

**Comment by bockthom** [comment]
Here is a very brief summary of the outcomes of our meeting today:
- Regarding the wrong column types: This might appear due to outdated `is.null` checks, so that the data frame is not correctly initialized. The problem should vanish as soon as all `is.null` checks for data sources are consistently updated to our new way of data initialization.
- For testing empty data or empty networks, we agreed to have a separate casestudy in our test data, in which all `*.list` files are empty. This way we can guarantee that we really have empty data and all tests relying on empty data need to use this new casestudy.
- There are still some pitfalls related to the reading problem after activity-based splitting, which we still need to figure out and explore in detail.

**Comment by nlschn** [comment]
I think (and I hope) that I just managed to fix the bug regarding the activity based splitting by simply re-setting the names of the `data.split` object to the vector of gathered data sources. This was discovered by @bockthom (thank you again) and it seems to fix the tests, but I don't quite get why, actually. Because 3 lines later (in line 161 in the new commit that will be up soon), `data.split` is overriden and so is `names(data.split)`, before the call to the setters of the data sources can trigger the hellish re-read of the data that caused the issue in the first place. But somehow it seems to work.

However, after some additional debugging, I found the causes of some other issues that made some tests fail:
- In `util-networks.R` in the function `get.sample.network` the ProjectData is generated from the ranges in the test data, but the flag `built.from.read.range.data` was not set to `TRUE` in the constructor.
- In `get.artifacts()` in `util-data.R` I recently added a `length(artifacts) == 0` check at the bottom in order to recognize whether the `artifacts` object is a `character(0)` That check worked, but I found out, that the `nrow(artifacts) == 0` check in the same if-condition returns `NULL` in some cases, causing tests to fail, because, apparently, if-statements cannot handle `NULL` values in the condition. Now I'm not quite sure how to resolve this. My idea would be to remove the `nrow` check completely, as it should yield the same result as the `length` check, shouldn't it (at least if the second one is 0 then the first one should be as well)?
