### ISSUE TITLE
Add a locking functionality for the splitting routine

### ISSUE THREAD

**Issue by hechtlC** [se-sic/coronet#179]
### Description

As we try to add a functionality to re-read the data sources for existing RangeData objects, as documented in #177, we want to add a locking functionality to prevent unintentional re-reading. 

### Motivation

The motivation behind this is is that we are currently making the used data, especially the additional data sources (PaStA, synchronicity, ...), re-readable/addable at any point in an analysis. This is not yet possible. But as we add this, we need a locking functionality to prevent the adding or re-reading and thus potentially the loss of already generated results. Moreover, we can optimize the splitting routine using this locking functionality by preventing the reading of all data sources when splitting (which is the case right now). When locked, we only use the already cached data to split the ProjectData object.

### Ideas for the Implementation

The implementation will be done by setting a flag in the ProjectData/RangeData object or by passing a parameter to the splitting and reading functionality. This is to be seen, which routine fits better.

### Additional Information

This issue is mainly to document the enhancement we already decided on and is a complementary issue to #177.

**Comment by hechtlC** [comment]
The concrete method to realize this locking functionality will be a "locked" flag in the `ProjectData` class. This can then be set to true or false by a lock/unlock function.

**Comment by bockthom** [comment]
Although we have believed that we do not need the locking functionality any more (see comment https://github.com/se-sic/coronet/issues/177#issuecomment-809369163), during debugging the failing tests in #201, it turned out that we still need the locking functionality in some special situations:

When we don't want to use issue data, but issue data is available, `get.issues()` will though be automatically called (e.g., in `extract.timestamps()`. If issue data is available but not yet read, the issue data is always read even if we don't want to. To prevent this, the locking functionality is needed.

_Implementation ideas:_ 
Let's have further configuration options in the project conf: `issues.lock`, `commits.lock`, `mails.lock`. These boolean flags can be set via the usual way on how to set/unset configuration options. Hence, this should not add lots of implementation efforts. As the project conf will be cloned during splitting, the configuration option will be automatically passed to RangeData objects during splitting. In the end, we only need to add additional checks to the getters to the main data sources and only read the data if it is not locked.

(Usually, we also should ask ourselves whether locking should also prevent setting data manually. However, this question is too complex to deal with now and, more importantly, does not affect #201, so I would postpone this specific question to the future, as it is a rather philosophical question :wink: )
