### ISSUE TITLE
Further improvements to splitting module

### ISSUE THREAD

**Issue by bockthom** [se-sic/coronet#187]
Here, we collect further ideas from PR #184 on how to improve the splitting module. Thanks to @clhunsen for your suggestions!

1. [x] Add utility function to obtain the bin labels (`bins.date`) from ranges: ~~`construct.bin.labels.from.ranges`~~ ``get.bin.dates.from.ranges`` [edited on 2024-02-29]
2. [x] Add bins attribute to list of split networks also in functions `split.network.time.based.by.ranges` and `split.networks.by.bins`. To be able to do that, we need functions like `construct.bin.labels.from.ranges` (see above) to extract the bins from the ranges. (See also the current occurrences of `attr(nets, "bins") = bins.date`). After adding this attribute in the mentioned functions, we do not need to set this attribute in the function `split.networks.time.based` anymore.
3. [x] When working on network-based splitting anyway (as in the previous item), we should check whether the splitting for networks works correctly with respect to the corner cases on sliding-window splitting that we have fixed in PR #244. 
4. [ ] ~~If we construct ranges in `split.networks.time.based` after Line 660 and after Line 668 (both using `construct.ranges(bins.date, sliding.window = ...)`), we could omit the if-else cascade in Lines 682ff. This would decrease the complexity of the functionality below.
https://github.com/se-sic/coronet/blob/78e99a14d8575f3146c607dbf68136669e7e4875/util-split.R#L660-L691~~
_(We don't want to implement the fourth suggestions, since it would add one additional, but unnecessary indirection, as `split.network.time.based.by.ranges` would in turn call `split.network.time.based`, and this would be one more indirection in the `else` case than what the current implementation does. Therefore, I have crossed out the last suggestion.)_ [edited on 2023-11-15]

All three suggestions should be easy to implement and should, therefore, easily improve the code of the splitting module.

**Comment by MaLoefUDS** [comment]
I have worked on the first two points and have a finished commit here: https://github.com/MaLoefUDS/coronet/commit/a18a9321380569b25e5af82a8069f5b2ed1e723e. I will not open a pull request just now though, as we discussed, to not interfere with this https://github.com/se-sic/coronet/pull/244. I will look into the corner cases (point three) from now on :)

**Comment by bockthom** [comment]
> I have worked on the first two points and have a finished commit here: [MaLoefUDS@a18a932](https://github.com/MaLoefUDS/coronet/commit/a18a9321380569b25e5af82a8069f5b2ed1e723e).

Thanks! I had a quick look at it, and your commit looks good to me (given that the functionality did not change, what we will hopefully see in the tests - did you already check whether the tests for the different kinds of splitting do also test for the bins attribute?). 
I just added a comment regarding the placement new helper function.

**Comment by MaLoefUDS** [comment]
I manually stepped through the code and checked that the corner cases we discovered in my last PR do not apply to activity-based network splitting, as they did to activity-based data splitting. 

This has mainly the reason, that the `id.column` of activity-based network splitting is not obtained from some metric of the network but artificially assigned in the form of a monotonic counter. Therefore we do not run into issues of multiple elements having the same `id` and resulting corner cases. 

There was also an issue that was caused by the `offset.end` calculation and how it was in the following in activity-based data splitting. The `offset.end` calculation seems to be identical in network splitting, but I was not able to find problems with it this time,  maybe because it it used differently. E.g., the check where we check if the last range should be dropped is different to both the version we had before in activity-based data splitting, as well as to the one we have right now (Should I update it to be consistent to the one data splitting we have right now?).

**Comment by MaLoefUDS** [comment]
Also about your last question regarding tests. In the last PR I added tests, that test for the validity of the `bins` parameter in data splitting. By "did you already check whether the tests for the different kinds of splitting do also test for the bins attribute?", do you mean I should add similar tests for network splitting? Or do you mean something else?
