### ISSUE TITLE
Support arbitrarily defined revision ranges for splitting

### ISSUE THREAD

**Issue by clhunsen** [se-sic/coronet#36]
[Edit by @bockthom on 2022-06-08: Some ideas from this issue are already outdated. Please find some updated information in today's [comment below](https://github.com/se-sic/coronet/issues/36#issuecomment-1150013062)]

In the future, it may be the case that we only use the `threemonth` selection process of Codeface. Here the reason why: In the end, the selection process only affects the identification heuristics for artifacts within commits (`commit_dependency` table of Codeface DB), while we may want to analyze further and different revision ranges (e.g., six-month time windows). For this case, we developed the splitting functionality that operates on the project-level data. While we are able to split data by abstract time windows (such as `3 months` or `6 months`), the splitting with explicit bins is more complicated, as the timestamps for the bins need to be identified.

Here the idea: We should do a version selection for our case studies and store those with the Codeface data somehow. For example, we could provide version-based splitting bins for all case studies or bins for specific time periods where the maintainer is a different person etc. In the end, the user does not need to bother about retrieving special bins (except there is the need for a new one), but only needs to configure a file name or version selection process.

Ideas for predefined bins:
- all major versions,
- all versions,
- time periods with different lead maintainer,
- ...

There are some questions now:
1. How do we integrate this into the code exactly?
2. Do we provide names for the selection process and the library does the rest (i.e., read the corresponding file from disk and pass the right parameters to the splitting functionality)?
3. Do we instruct the user to provide file names and proper calling of methods (a how-to would be needed anyway)?
4. Is this kind of a bulk mechanism? (which would support idea 2)

What are your thoughts? Are there questions?

**Comment by bockthom** [comment]
Since quite some time has passed since this issue was created, `coronet` has slightly :wink: changed, the all above stated information is partly outdated or rather irrelevant, and therefore can be ignored. Here follows the information on how this issue should be solved now:

We would like to have a new "additional data source", to be called something like `custom.timestamps` (just a working name, proper ideas on how to call this data source are welcome :thinking: ). In particular, the following tasks need to be implemented:
- Add a new read function for the new data source to `util-read.R`. File format: `*.list` (i.e., semicolon separated). Two columns: "name", "date". Example: 
 ```R
"v3.0";"2020-01-02 15:00:00"
"v3.1.2";"2020-02-03 11:11:11"
"v3.1.12";"2020-05-05"
```
- Add the new data source to the project data object and make reading it configurable (`util-data.R.` and `util-conf.R`). This includes also adding a getter and a setter, etc. In addition, in contrast to all the existing data sources, we would like to support arbitrary filenames to be read from (for example, to have one file containing release dates and one file containing event dates such as the buy-in of companies or creation of a new fork). The default should be to read from a generically named file, but one should be able to provide another filename instead to be able to choose between different of these files.
- Add a parameter to `split.data.by.bins` or `split.data.by.ranges` (or/and similar splitting functions, depending on where it would make sense) to use the "custom timestamps" of the data object for splitting instead of passing time stamps manually. It may also be worth to think about adding a new wrapper function for that that contains the data source name within the function name (not sure if this is necessary.)
